### ISSUE TITLE
function/symbol 'RaptorQ_Enc' not found in library '/usr/local/lib/libRaptorQ.dylib'

### ISSUE THREAD

**Issue by siavashk** [mk-fg/python-libraptorq#3]
When I try to encode a string similar to the wiki, e.g. `data = 'some input string' * 500`, on Python 2.7, I get the following error:

`AttributeError: function/symbol 'RaptorQ_Enc' not found in library '/usr/local/lib/libRaptorQ.dylib': dlsym(0x7f7f76cf57e0, RaptorQ_Enc): symbol not found`

I have cloned, built and install libRaptorQ from https://fenrirproject.org/Luker/libRaptorQ/tree/master.

There are no references to `RaptorQ_Enc` in libRaptorQ source code. In fact the only place where `RaptorQ_Enc` appears in this project is in the documentation under `doc/libRaptorQ.tex`

It would be nice if the developers would suggest a fix or a workaround.

**Comment by mk-fg** [comment]
Iirc Luca wanted to change API in the new release quite a bit, making it way easier and more robust, but that wasn't around in stable versions when this wrapper was written, so should be updated.
Shouldn't be that hard to do, but not sure when I'll get to it, and should probably update the thing to use py3 while at it (as I've migrated away from 2.7 since then)...

In the meantime, guess you can use older release of the lib with the module, if you really want it, or maybe a command-line tool that comes with the lib as an interface - one was in the works, I think, as per https://www.fenrirproject.org/Luker/libRaptorQ/issues/9
(which, damn, I should've replied to 6mo ago and completely forgot about...)

**Comment by mk-fg** [comment]
> the only place where RaptorQ_Enc appears in this project is in the documentation under doc/libRaptorQ.tex

I'd suspect that it's just a case of an outdated documentation.

**Comment by mk-fg** [comment]
> change API in the new release

I think it's the change that happened in 0.1.X -> 0.2.X, so guess workaround would be using 0.1.X version, e.g. 0.1.9 (last one I seem to have package for).

**Comment by mk-fg** [comment]
Also note that libRaptorQ README says:
```
stable  release: v0.1.9
current release: v1.0.0-prealpha
CURRENTLY BREAKING APIs, stick with the stable release
UPDATE: almost finished the brakage, things should be stable enough
```

**Comment by siavashk** [comment]
Thanks for getting back to me. Per your advice, I am trying to build with v.0.1.9. I am having issues with that too. But I guess I will post problems on the relevant project page.

**Comment by siavashk** [comment]
I can encode. Here are the steps in case someone else runs into trouble:

1. Checkout v0.1.9 from https://fenrirproject.org/Luker/libRaptorQ/tree/master
2. Checkout Eigen 3.3 from https://github.com/RLovelett/eigen.git
3. Remove LD flags `-z,now,-z,relro` from CMakeLists.txt in libRaptorQ.
4. Remove RaptorQ_Static target from CMakeLists.txt
5. Configure and generate CMake with only DYNAMIC_LIB option enabled.
6. Build and install libRaptorQ.

Following these steps, I can encode my data in Python. I am going to try to decode the data, if I run into trouble, I might bug you again and open a new issue.

**Comment by mk-fg** [comment]
\o/

Though I'm confused about RaptorQ_Static and DYNAMIC_LIB apparently being non-default for you.
On linux, was building the thing with a simple `cmake` - https://github.com/mk-fg/archlinux-pkgbuilds/blob/master/libraptorq-git/PKGBUILD#L23
Guess cmake/compiler defaults might be different on OSX, and maybe it was also changed in libRaptorQ repo.

I think cffi bindings like in this module can actually work without dynamic linking (“ABI” versus “API” level) with just minor code changes (i.e. switch to API mode in cffi), if useful for specific setup.
With a drawback of requiring compiler to build/install that python module from source, of course.

**Comment by siavashk** [comment]
`RaptorQ_Static` and `DYNAMIC_LIB` were default for me. It is just that the linker would fail with the `RaptorQ_Static` option enabled. So I experimented with different configurations until I could build it.
