### ISSUE TITLE
Sending a JPEG buffer through an Encoding-Decoding Pipeline

### ISSUE THREAD

**Issue by siavashk** [mk-fg/python-libraptorq#4]
I am trying to encode-decode a jpeg file using your framework. I can encode the data, but I can’t decode it back.

Here is what I have done:

1. Read the data in binary and stored it in a string which kind of looks like this: '����C.. ����'
2. Fed the data through the encoder as described in the README with the same parameters.
3. Fed the encoded data back to the decoder (as described in the README) to reconstruct the jpeg.

However, I get an error when I try to create the decoder, i.e. `with RQDecoder(otiScheme, otiCommon) as dec:`. The error is the following:
`ile "/Library/Python/2.7/site-packages/libraptorq/__init__.py", line 145, in open
    self._ctx = self._ctx_init[0](*self._ctx_init[1])
OverflowError: integer 201595027472 does not fit 'uint32_t’`

I understand that this is an overflow, but I don’t know why `oti_common` is such a large number. Am I missing something? Is jpeg data not allowed?

**Comment by siavashk** [comment]
I tried the `rq` program that comes with the package. I can encode/decode with that, so there is something wrong with what I am doing.

**Comment by siavashk** [comment]
This is strange. `oti_common` is the same large number if I encode through `rq` or through the sample code in the README.

**Comment by mk-fg** [comment]
Oh crap, sorry, it's the dumbest thing in the README: `RQDecoder(oti_scheme, oti_common)`
While it **should be**: `RQDecoder(oti_common, oti_scheme)`

It's hard to spot the swapped args, and error message doesn't help figure out wth is going on there at all.
Fixed now, though it's just a oneliner README tweak, no need to update anything, just swap them in your code as well.

**Comment by mk-fg** [comment]
Shows how many people have actually used the thing I guess, if you're the first to stumble into this :)

**Comment by siavashk** [comment]
Something that you might want to consider is reworking the `_decode` function in the `rq` script. If you look at https://github.com/mk-fg/python-libraptorq/blob/master/libraptorq/__main__.py#L111-L139 you will notice that the input argument `opts` is not actually used throughout the function.

**Comment by mk-fg** [comment]
I think it's there for consistency, and in case there'll be a need for any decode-specific options.
