### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by fionafibration** [mk-fg/python-libraptorq#7]
Is there any chance of Python 3 support for this module? I'd like to use it in a few projects I'm working on, but Python 2 is unsuitable for the type of code I'm working on.

**Comment by mk-fg** [comment]
Haven't stumbled upon any new project where I needed it myself, unfortunately.
Conversion should be relatively straightforward though - cffi was probably py2/py3 from the start and module works with binary data, so just adding a bunch of b's before all used bin-strings might do it.
Have no plans for such conversion, alas, but would suggest just updating it yourself, if useful enough in a non-trivial project, given that it should be relatively straightforward.

**Comment by fionafibration** [comment]
Ok, do you know anything about compiling libRaptorQ on Windows? The
libRaptorQ page says it isn't supported on Windows, but it mentions Visual
Studio 2015, so I don't know if that information is out of date.

**Comment by mk-fg** [comment]
No, never tried building it there and never looked into it.
I'd suggest looking at the gitlab instance for libRaptorQ (under fernir project), as I've seen quite a few questions asked and answered there in the past.
Also, it had tex documentation with pdf's generated from it for releases, maybe there's more info there than on webpages.
